
export default {
  LOGIN: "/authLogin.json",
  LOGIN_OTP_GENERATE: "/bankingservices/public/otp/loginOtpGenerate",
  LOGIN_OTP_VERIFY: "/verifyOtp.json",
  LOGOUT: "/authLogout.json",
  featureCheck: "/featureCheck.json",
  REFRESH_TOKEN: "/bankingservices/public/refreshtoken",
  GET_ALL_EXCHANGE_RATES: '/getCrossCurrencyRates.json',
  calLoanDep: "/calLoanDep.json",
  updatecompanyimage: "/updatecompanyimage.json",
  companyprofileimage: "/companyprofileimage.json",

  common: {
    otherBanksList: "/otherBanksList.json",
    countryList: "/getSwiftCountry.json",
    getRemarksCategory: "/bankingservices/userActivity/getRemarksCategory",
  },

  portfolio: {
    getBalances: "/getBalances.json",
  },

  profile: {
    getProfileDetails: "/get.json",
    getImage: "/getImage.json",
    deleteImage: "/bankingservices/profile/deleteImage",
    uploadImage: "/bankingservices/profile/uploadImage",
    changePassword: "/changePwd.json",
  },

  newCustomer: {
    getDataList: "/bankingservices/public/information/dataList",
    getBranchDetails: "/bankingservices/public/custOnboard/getBranchDetails",
    termsAndConditions: "/termsAndConditions.json",
    createNewCustomer: "/bankingservices/public/custOnboard/createCust",
    faceMatch: "/bankingservices/public/kyc/faceMatch",
    verifyLiveness: "/bankingservices/public/kyc/verifyLiveness",
    getKycDetails: "/bankingservices/public/kyc/getKycDetails",
    validateId: "/validateId.json",
    branchList: "/bankingservices/public/information/branchList",
    customerCreateOtpGenerate: "/customerCreateOtpGenerate.json",
    createNewCustomer: "/bankingservices/public/customerregister/createNewCustomer",
    generateOtp: "/customerCreateOtpGenerate.json",
    validateOtp: "/customerotpValidation.json",
    validateIdCheck: "/bankingservices/public/customerregister/idcheck",
  },

  beneficiary: {
    verifyAddInternalBene: "/internalBeneficiaryVerification.json",
    confirmAddInternalBene: "/addInternalBeneficiary.json",
    confirmOtherBene: "/addThirdpartyBeneficiary.json",
    verifyOtherBene: "/otherBeneficiaryVerification.json",
    confirmInternationalBene: "/addThirdpartyBeneficiary.json",
    verifyInternationalBene: "/otherBeneficiaryVerification.json",
  },

  transfers: {
    getAllBeneficiaries: "/getAllBeneficiaries.json",
    changeBeneficiaryImage: "/bankingservices/beneficiary/updateBeneImage",
    deleteBeneficiaryImage: "/bankingservices/beneficiary/deleteBeneImage",
    getBeneficiaryImages: "/getBeneImages.json",
    FUND_TRANSFER_VERIFY: "/verify.json",
    FUND_TRANSFER_CONFIRM: "/confirm.json",
    repeatTransactions: '/transactions.json'
  },

  account: {
    fullStatement: "/fullStatement.json",
    getAccountMiniStatement: "/getAccountMiniStatement.json",
    getAccounts: "/getAll.json",
    getAccountClasses: "/bankingservices/accountClass/getAccountClasses",
    createCASAAccountVerify: "/createCASAAccountVerify.json",
    createCASAAccountConfirm: "/createCASAAccountConfirm.json"
  },
  loans: {
    uploadDocument: "/bankingservices/loan/loandocuments",
    microloan: "/bankingservices/loan/microloan"
  },
  deposit: {
    currencyList: "/currencyList.json",
    getProducts: "/getProducts.json",
    getAll: "/getAll.json",
    verify: "/depositVerify.json",
    confirm: "/depositConfirm.json",
    getDepositAccountDetails: '/getDepositAccountDetails.json',
    getDepositAccountStatement: '/getDepositAccountStatement.json'
  },
};

export const COUNTRYLIST = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic (CAR)",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo, Democratic Republic of the",
  "Congo, Republic of the",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates (UAE)",
  "United Kingdom (UK)",
  "United States of America (USA)",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City (Holy See)",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
